name: Deploy

on:
  push:
    tags:
      - '*'
  release:
    types:
      - published

jobs:
  check-tests:
    name: Check tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: CI

  deploy:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    needs: check-tests
    if: needs.check-for-tests.outputs.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install setuptools wheel
      - name: Build the wheel
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-actions-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
